services:
  # Backend API
  backend:
    build:
      context: .
      dockerfile: Dockerfile
      target: backend
    container_name: jsr-backend
    restart: always
    environment:
      - NODE_ENV=production
      - PORT=3000
      - MONGODB_URI=${MONGODB_ATLAS_URI}
      - JWT_SECRET=${JWT_SECRET}
      - SUPABASE_URL=${SUPABASE_URL}
      - SUPABASE_SERVICE_ROLE_KEY=${SUPABASE_SERVICE_ROLE_KEY}
    ports:
      - "127.0.0.1:3000:3000"
    networks:
      - jsr-network
    deploy:
      resources:
        limits:
          memory: 512M
          cpus: '0.5'

  # Frontend client
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
      target: frontend
      args:
        - VITE_API_URL=${API_URL}
        - VITE_SUPABASE_URL=${SUPABASE_URL}
        - VITE_SUPABASE_ANON_KEY=${SUPABASE_ANON_KEY}
    container_name: jsr-frontend
    restart: always
    environment:
      - NODE_ENV=production
      - VITE_API_URL=${API_URL}
      - VITE_SUPABASE_URL=${SUPABASE_URL}
      - VITE_SUPABASE_ANON_KEY=${SUPABASE_ANON_KEY}
    ports:
      - "127.0.0.1:3001:80"
    networks:
      - jsr-network
    deploy:
      resources:
        limits:
          memory: 128M
          cpus: '0.2'

  # Admin dashboard
  admin:
    build:
      context: .
      dockerfile: Dockerfile
      target: admin
      args:
        - VITE_API_URL=${API_URL}
    container_name: jsr-admin
    restart: always
    environment:
      - NODE_ENV=production
      - VITE_API_URL=${API_URL}
    ports:
      - "127.0.0.1:3002:80"
    networks:
      - jsr-network
    deploy:
      resources:
        limits:
          memory: 128M
          cpus: '0.2'

networks:
  jsr-network:
    driver: bridge

volumes:
  mongodb_data: 