version: '3.8'

services:
  # Backend API
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: jsr-backend
    restart: always
    environment:
      - NODE_ENV=production
      - PORT=3000
      - MONGODB_URI=${MONGODB_ATLAS_URI}
      - JWT_SECRET=${JWT_SECRET}
      - SUPABASE_URL=${SUPABASE_URL}
      - SUPABASE_SERVICE_ROLE_KEY=${SUPABASE_SERVICE_ROLE_KEY}
    ports:
      - "127.0.0.1:3000:3000"
    volumes:
      - ./shared:/app/shared
    networks:
      - jsr-network

  # Frontend client
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: jsr-frontend
    restart: always
    environment:
      - NODE_ENV=production
      - VITE_API_URL=${API_URL}
      - VITE_SUPABASE_URL=${SUPABASE_URL}
      - VITE_SUPABASE_ANON_KEY=${SUPABASE_ANON_KEY}
    ports:
      - "127.0.0.1:3001:80"
    volumes:
      - ./shared:/app/shared
    networks:
      - jsr-network

  # Admin dashboard
  admin:
    build:
      context: ./admin
      dockerfile: Dockerfile
    container_name: jsr-admin
    restart: always
    environment:
      - NODE_ENV=production
      - VITE_API_URL=${API_URL}
      - VITE_SUPABASE_URL=${SUPABASE_URL}
      - VITE_SUPABASE_ANON_KEY=${SUPABASE_ANON_KEY}
    ports:
      - "127.0.0.1:3002:80"
    volumes:
      - ./shared:/app/shared
    networks:
      - jsr-network

networks:
  jsr-network:
    driver: bridge

volumes:
  mongodb_data: 