version: '3.8'

services:
  # Backend API
  backend:
    build:
      context: .
      dockerfile: Dockerfile
      target: backend
    container_name: jsr-backend
    restart: always
    environment:
      - NODE_ENV=production
      - PORT=3000
      - MONGODB_URI=${MONGODB_ATLAS_URI}
      - JWT_SECRET=${JWT_SECRET}
      - SUPABASE_URL=${SUPABASE_URL}
      - SUPABASE_SERVICE_ROLE_KEY=${SUPABASE_SERVICE_ROLE_KEY}
    ports:
      - "127.0.0.1:3000:3000"
    networks:
      - jsr-network

  # Frontend client
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
      target: frontend
    container_name: jsr-frontend
    restart: always
    environment:
      - NODE_ENV=production
    ports:
      - "127.0.0.1:3001:80"
    networks:
      - jsr-network

  # Admin dashboard
  admin:
    build:
      context: .
      dockerfile: Dockerfile
      target: admin
    container_name: jsr-admin
    restart: always
    environment:
      - NODE_ENV=production
    ports:
      - "127.0.0.1:3002:80"
    networks:
      - jsr-network

networks:
  jsr-network:
    driver: bridge

volumes:
  mongodb_data: 