name: Deploy to VPS

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup SSH
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.VPS_SSH_KEY }}

      - name: Deploy to VPS
        run: |
          ssh -o StrictHostKeyChecking=no ${{ secrets.VPS_USER }}@${{ secrets.VPS_HOST }} << 'EOF'
            cd apps/jsr
            
            # Update code
            git pull origin master

            # Make sure .env file exists for Docker Compose to use
            if [ ! -f .env ]; then
              echo "Creating .env file from template"
              cp .env.production .env
            fi
            
            # Build and start services with workspace npm package approach
            docker compose down
            
            # Build and start services incrementally to manage disk space
            echo "Building and starting MongoDB..."
            docker compose up -d mongodb
            
            echo "Building and starting Backend..."
            docker compose up -d --build backend
            
            echo "Building and starting Frontend..."
            docker compose up -d --build frontend
            
            # Final disk space check
            echo "Final disk space:"
            df -h /
          EOF