name: Deploy to VPS

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup SSH
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.VPS_SSH_KEY }}

      - name: Deploy to VPS
        run: |
          ssh -o StrictHostKeyChecking=no ${{ secrets.VPS_USER }}@${{ secrets.VPS_HOST }} << 'ENDSSH'
            cd apps/jsr
            
            # Force clean git update
            git fetch origin
            git reset --hard origin/master
            
            # Free up resources before building
            echo "Stopping previous containers to free resources..."
            docker compose -f docker-compose.prod.yml down
            
            # Aggressive cleanup of Docker cache and resources
            echo "Aggressive cleaning of Docker resources..."
            docker system prune -af --volumes
            docker builder prune -f
            docker image prune -af
            
            # Enable BuildKit for more efficient builds
            echo "Setting up Docker BuildKit..."
            export DOCKER_BUILDKIT=1
            export DOCKER_DEFAULT_PLATFORM=linux/amd64
            
            # Build the full stack with forced rebuild, no cache
            echo "Building containers with clean forced rebuild..."
            docker compose -f docker-compose.prod.yml build --no-cache --progress=plain
            
            echo "Starting all containers..."
            docker compose -f docker-compose.prod.yml up -d

            # Final disk space check
            df -h /
          ENDSSH