name: Deploy to VPS

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup SSH
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.VPS_SSH_KEY }}

      - name: Deploy to VPS
        run: |
          ssh -o StrictHostKeyChecking=no ${{ secrets.VPS_USER }}@${{ secrets.VPS_HOST }} << 'EOF'
            cd apps/jsr
            
            # Update code
            git pull origin master

            # Make sure .env file exists for Docker Compose to use
            if [ ! -f .env ]; then
              echo "Creating .env file from template"
              cp env.example .env
              
              # Set required environment variables
              sed -i "s|MONGODB_ATLAS_URI=.*|MONGODB_ATLAS_URI=${{ secrets.MONGODB_ATLAS_URI }}|g" .env
              sed -i "s|JWT_SECRET=.*|JWT_SECRET=${{ secrets.JWT_SECRET }}|g" .env
              sed -i "s|SUPABASE_URL=.*|SUPABASE_URL=${{ secrets.SUPABASE_URL }}|g" .env
              sed -i "s|SUPABASE_ANON_KEY=.*|SUPABASE_ANON_KEY=${{ secrets.SUPABASE_ANON_KEY }}|g" .env
              sed -i "s|SUPABASE_SERVICE_ROLE_KEY=.*|SUPABASE_SERVICE_ROLE_KEY=${{ secrets.SUPABASE_SERVICE_ROLE_KEY }}|g" .env
              sed -i "s|API_URL=.*|API_URL=https://api.jsresources.dev|g" .env
              sed -i "s|DOMAIN_NAME=.*|DOMAIN_NAME=jsresources.dev|g" .env
              sed -i "s|ADMIN_EMAIL=.*|ADMIN_EMAIL=${{ secrets.ADMIN_EMAIL }}|g" .env
              sed -i "s|NODE_ENV=.*|NODE_ENV=production|g" .env
            else
              # Update the .env file with the latest production values
              echo "Updating existing .env file with production values"
              # Update MongoDB Atlas URI
              sed -i "s|MONGODB_ATLAS_URI=.*|MONGODB_ATLAS_URI=${{ secrets.MONGODB_ATLAS_URI }}|g" .env
              # Update other sensitive environment variables
              sed -i "s|JWT_SECRET=.*|JWT_SECRET=${{ secrets.JWT_SECRET }}|g" .env
              sed -i "s|SUPABASE_URL=.*|SUPABASE_URL=${{ secrets.SUPABASE_URL }}|g" .env
              sed -i "s|SUPABASE_ANON_KEY=.*|SUPABASE_ANON_KEY=${{ secrets.SUPABASE_ANON_KEY }}|g" .env
              sed -i "s|SUPABASE_SERVICE_ROLE_KEY=.*|SUPABASE_SERVICE_ROLE_KEY=${{ secrets.SUPABASE_SERVICE_ROLE_KEY }}|g" .env
              sed -i "s|NODE_ENV=.*|NODE_ENV=production|g" .env
            fi
            
            # Make sure the scripts are executable
            chmod +x scripts/*.sh
            
            # Run the setup script to ensure shared directory exists
            echo "Setting up monorepo structure..."
            ./scripts/setup-monorepo.sh
            
            # Run the check files script to ensure required files exist
            echo "Checking required files..."
            ./scripts/check-files.sh
            
            # Build and start services
            docker compose -f docker-compose.prod.yml down
            docker compose -f docker-compose.prod.yml build --no-cache
            docker compose -f docker-compose.prod.yml up -d
            
            # Clean up unused Docker resources
            docker system prune -af --volumes
            
            # Update Nginx configuration if needed (requires sudo access for the user)
            if [ -f nginx-host-config.conf ] && [ -x "$(command -v sudo)" ]; then
              echo "Updating Nginx configuration..."
              sudo scripts/update-nginx-config.sh
            fi
            
            # Final disk space check
            echo "Final disk space:"
            df -h /
          EOF